The corona crisis is having major impacts onto our lives right now. COVID-19 is affecting our minds, consuming our thoughts, and changing our daily habits in ways unimaginable before. Extreme precautions have been and are being taken to prevent the spread of virus. Everyday, we are learning more and more about this new ennemy. And every day we are having to re-evaluate our [previoous] considerations and our projections. But the speed at which COVID-19 related events are happening makes it difficult to conduct careful randomized studies: to investigate mortality [rate] and appropriate medical interventions in a controlled manner. That is why we have been - till the present moment - limited mainly to observational data. It is of the utmost importance to systematically record these observations and to assess them correctly.

The theory of causality can be an appropriate theoretical tool to investigate causal effects in observational studies, when certain conditions are met. Observational studies are data collections without experimental control, which is now the case with the current corona crisis. In contrast, approval procedures for the pharmaceutical industry requires randomised double-blind experiments. Experiments are the golden standard for investigating effects and side effects.Unfortunately, however, they are not always possible, and this pandemic has made that already abundantly clear.

My colleagues and I, who are doing research in this area, are convinced that in the current situation causal inferential statistics can help clarify crucial, but still open, questions for the general public, politicians and scientists.


** Request for critical reviews, improvements and cooperation
As time is short, I'm publishing this draft with suggestions for data collection, publication and analysis here on GitHub as a "living" document.
This way it is possible to quickly and publically 
- discuss and work out these plans together
- compile data
- publish and review statistical models.

Please:
# - Publish and share the link to this document (and its GitHub repository) to help clarify the open questions in the Corona crisis through statistical causal research and to spread the knowledge about these possibilities.
# - Write a letter of support for the collection and publication of [[data][required data]].
# - Compile [[data][required data]].
- [[https://github.com/gkappler/CausalCovid-19/issues][Ask critical questions about the arguments and considerations in this document -- even as a layman.]]
- Work on the document if you feel able to do so (fork in the upper right corner, edit and pull request).
- Suggest corrections if you see errors in the considerations in this document.
- Contribute statistical regression models that can be used as a basis for causal estimation.

How dangerous is Covid19? Which treatments work? There is a lot of debate at present as to whether people die "of" or "with" corona.
That is: whether corona *caused* the death of a person, and how dangerous Covid-19 is compared to influenza, for example.
Although this question concerns all measures taken, it is unfortunately not possible to give definite answers based solely on the published figures thus far. Representative antibody tests can give us some clarifications; autopsies of the deceased oned may give us valuable information through the expert opinion.

The doctors in the intensive care units have to make treatment decisions on a daily basis and on the spot.
Recently, several doctors in Europe and the USA came forward to the public and reported their experiences with intubation in Covid-19 patients. They were very surprised that even with such low oxygen saturation of about 50% many of their patients survive the disease without intubation, but the intubated patients mostly die.
(https://www.nytimes.com/2020/04/14/nyregion/new-york-coronavirus.html, https://www.youtube.com/watch?v=bp5RMutCNoI).
Such experiences are anecdotal and not scientific. Nevertheless, it is important and right that doctors  exchange on such matters anecdotally. These doctors should find efficient methods of treatment to help patients in intensive care units in the best possible way and not to treat them to death, with the of best intentions, with treatments that are perhaps harmful for this new disease. Doctors learn from  observations during their work and through exchanges and - unfortunately - through trial, error and success. Scientific, randomized studies on the treatment success of interventions do not yet exist.

However, there are statistical methods of causal inferential statistics that can estimate *without* randomized studies the medical measures that causally promote or negatively influence healing:
The theory of causal effects by R. Steyer or propensity score matching according to Rubin.
Put simply, these procedures systematize the analysis of anecdotal experiences and mathematically correct the bias that is inevitable in non-randomized observations.
On the basis of sufficient data, these methods allow 
1. to determine the effectiveness of medical measures through systematic observation and recording
3. to calculate a much needed estimate of the average mortality of Covid19 in the total population,
4. to reliably quantify the conditional risk of death in case of infection, for persons of a certain age, sex and also for certain pre-existing conditions.
5. to estimate the consequences of evidence-based herd immunisation plans, i.e. which 60%-70% of the population with the lowest risk of developing the disease, and the risk of these groups of people dying of the disease.
6) These estimated consequences of controlled flock immunisation can then be compared to assumptions about the risk of vaccination side effects.
These questions are of the utmost urgency in the current situation in order to advise hospital doctors, concerned citizens and politicians on measures to be taken. Unfortunately, epidemiological model calculations cannot answer these causal questions.
Instead, informed but ultimately hypothetical assumptions are used to make model predictions.

The theory of causality was developed for circumstances such as the corona pandemic to estimate causal effects in observational studies, i.e. when it is not possible to form a control and experimental group.
To estimate causal inference models, it would be necessary to collect a large amount of data available in hospitals and health authorities for each individual case and to make them available anonymously.

Data at the level of individual cases are therefore urgently needed for the best possible research into the risk of the disease and the effectiveness of medical measures. But they are missing.
Unfortunately, at present moment almost exclusively summarised case numbers are published, with different breakdowns by country, sex and age. On the basis of these case numbers, i.e. without data on the level of individual cases, the above-mentioned most pressing questions cannot be answered. Only China has provided data on infected persons, on the basis of which important and high-ranking published studies have already been made possible.
- https://www.thelancet.com/journals/laninf/article/PIIS1473-3099(20)30243-7/fulltext 
- https://www.bmj.com/content/369/bmj.m1327

We suggest that the central collection and publication of this data be arranged immediately. These health data are protected by laws for obvious privacy reasons. This can be done anonymously. We are seeing how our Western democracies are ready to consider and adapt the need for China's authoritarian curfew and local data monitoring measures to contain the disease. Western democracies should also consider whether to lift privacy restrictions for the sick and the deceased for purpose of data collection. It would not be less of an intrusion into the social fabric of free societies, which is what they are doing now. With the Chinese example, we have seen how easing of data protection, for people who contacted the desease, provided valuable and practical knowledge about Covid-19 disease.

While there is a conspicuous lack of open data for research into the virus-induced Covid-19 disease, an exemplary open research situation can be observed in the study of the SARS-Cov2 genome:
the necessary data for the scientific community are openly available and allow an unprecedented acceleration of research (see European Commission https://horizon-magazine.eu/article/covid-19-how-unprecedented-data-sharing-has-led-faster-ever-outbreak-research.html)

Zumindest die freiwillige Freigabe der Daten durch Patienteneinverständnis sollte ab sofort eingeholt werden, und eine entsprechende Dateninfrastruktur des Europäischen Center of Desease Control vorbereitet werden.
Für bereits verstorbene Patienten sind wir der Überzeugung, dass eine Rechtsgüterabwägung die Nutzung dieser anonymisierten Daten ebenso oder leichter zulässt als die Erfassung von Bewegungsdaten der Bevölkerung.
Wir wollen eine öffentliche Diskussion über den Umgang mit Daten zur Wissenschaftlichen Untersuchung in dieser Corona-Krise anregen.

Katastrophen sind plötzlich und unübersichtlich.
Um in zukünftigen Katastrophen angemessen reagieren zu können, scheint es uns ganz besonders wichtig, aus dieser Katastrophe zu lernen, wie schneller ein gutes Bild der Lage erlangt werden kann.
Daher regen wir an, die Veröffentlichung anonymisierter Daten zu den Verstorbenen bei zukünftigen Pandemien als gesetzlichen Automatismus im Seuchenschutzgesetz zu verankern.
Nur auf diese Weise ist gewährleistet, dass die internationale Forschergemeinschaft mit im Seuchenfall gebotener Geschwindigkeit und Aktualität die Gefährlichkeit der Erkrankung erforschen und evidenzbasierte Hinweise für praktische Ärzte geben kann, welche der getroffenen medizinischen Maßnahmen wirken und zu warnen, welche Maßnahmen schaden.

** Übersterblichkeit, Kausalitätstheorie und Zufallsexperiment
Die Kausalitätstheorie nach Rolf Steyer beginnt mit einer formalen Begriffsklärung durch das Zufallsexperiment.
Zur verständlichen Beschreibung der Theorie in Bezug auf Corona die reduzierteste Fassung ohne Berücksichtigung der Zeitpunkte oder des Krankheitsverlaufs:
- Zur Testung wird eine Person /U=u/ aus der Population ausgewählt (nicht randomisiert, sondern gemäß Testprotokoll).
- Das Testergebnis der Person wird erhoben, /X=x/. 
- Kovariaten werden erhoben /Z=z/ (Alter, Geschlecht und Vorerkrankungen etc..)
- Erkrankt die Person (/S=1/) oder bleibt sie asymptomatisch (/S=0/)
- Verstirbt (/Y=0/) oder heilt (/Y=1/) die Person?

Wahrscheinlichkeitstheoretisch sind dies Zufallsvariablen
- /U : \Omega \rightarrow/ Population
- /X : \Omega \rightarrow {0,1}/
- /Z : \Omega \rightarrow Z_{1} \times...\times Z_{n}/
- /S : \Omega \rightarrow {0,1}/
- /Y : \Omega \rightarrow {0,1}/

*** Teststichprobe und Population, Infektion und Test
Die Testung und die Auswahl der Stichprobe gewährleistet keine direkte Einschätzung, wieviele Personen in der Bevölkerung wirklich infiziert sind. 

Dazu müssten im obigen Zufallsexperiment die Verteilung der Probanden /U/ durch eine randomisierte/repräsentative Auswahl /U/' ersetzt werden.
- Eine Person /U'=u/ wird gleichverteilt aus der Population ausgewählt (randomisiert, wird aus test-ökonomischen Gründen nicht/kaum duchgeführt).
Die Erkrankung an Covid-19, /X'/, kann nur indirekt durch Tests erhoben werden.
Tests sind niemals absolut zuverlässig sondern durch Sensititivtät und Spezifizität gekennzeichnet, in bedingten Wahrscheinlichkeiten ausgedrückt[fn::https://www.centerforhealthsecurity.org/resources/COVID-19/serology/Serology-based-tests-for-COVID-19.html]:
- Sensitivität: /1-P(X'=1 | X=0)/
- Spezifizität: /1-P(X'=0 | X=1)/


*** Was ist die Übersterblichkeit durch Corona in der erhobenen Stichprobe?
Die Anteile (Wahrscheinlichkeiten) der versterbenden Personen in der Testpopulation sind 
- wenn test-negativ: /P(Y=0 | X=0)/,
- wenn test-positiv: /P(Y=0 | X=1)/.

Der durchschnittliche kausale Effekt einer Covid-19 Erkrankung auf die Sterblichkeit innerhalb der getesteten Stichprobe entspricht der Differenz dieser Wahrscheinlichkeiten /P(Y=0 | X=1)-P(Y=0 | X=0)/ und kann als durch *Covid-19 bedingte Übersterblichkeit innerhalb der Stichprobe* interpretiert werden.
Hier stellen sich grundsätzliche Probleme:
- Die Stichprobe ist nicht repräsentativ für die Gesamtbevölkerung.
- Die Wahrscheinlichkeit mit negativem Test zu versterben ist anhand der erfassten Testdaten nicht möglich.
  Diese Wahrscheinlichkeit könnte jedoch auf Basis veröffentlichter Sterberaten der Vorjahre abgeschätzt werden.
- Die Zufallsvariablen der Genesung /Y/ kann erst nach dem Ende der Erkrankung erhoben werden. 

Für Personen, die durch Geschlecht, Alter und Vorerkrankungen /Z=z/ charakterisiert sind, und 
- positiv auf Covid19 getestet wurden, ist das bedingte Sterberisiko /P(Y=0 | Z=z,X=1)/,
- negativ auf Covid19 getestet wurden, ist das bedingte Sterberisiko /P(Y=0 | Z=z,X=0)/,
Der /Z/-bedingte durchschnittliche kausale Effekt von Covid19 auf die Sterberate ist definiert als die Differenz dieser bedingten Wahrscheinlichkeiten: /ACE_{Z=z}(Y | X) = P(Y=0 | Z=z,X=1) - P(Y=0 | Z=z,X=0)/.
Dieser bedingte durchschnittliche Effekt /ACE_{Z=z}(Y | X)/ is spezifisch für Personen, die durch Kovariaten /Z=z/ (Alter, Vorerkrankungen, etc.) charakterisiert sind, und für diese Gruppe definiert als der Mehr-Anteil der versterbenden Personen, die Covid-19 positiv getestet wurden, über die zu erwartende Sterblichkeitsrate von Covid-19 negativ getesteten Personen hinaus.
*Es handelt sich also um die Covid-19 bedingte Übersterblichkeit von Personen mit Kovariaten Z=z.* 

*** Verallgmeinerung auf die Bevölkerung
**** Kausale Erwartungstreue 
Definitionen
1. Der (/Z=z/) *-bedingte kausal erwartungstreue Erwartungswert* von /Y/ gegeben /X=x/ ist definiert als

   CUE_{Z=z}(Y | X=x) = \sum_u E_{Z=z}(Y | U=u,X=x)P_{Z=z}(U=u).
2. Die /Z/ *-bedingte kausale Regression* /E_{Z=z}(Y | X)/ ist kausal erwartungstreu, wenn für alle /Z=z/

   /E(Y | Z=z, X=x)/ = CUE_{Z=z}(Y | X=x).

Es ist beweisbar, dass /E_{Z=z}(Y | X)/ kausal erwartungstreu ist, wenn mindestens eine folgender Bedingungen erfüllt ist:
1. Die Überlebenswahrscheinlichkeit /E(Y | X, U, Z)/, bedingt auf Person /U/ mit Testung /X/ und Kovariaten /Z/, fast sicher (d.h. für alle Kovariaten /Z=z/ mit /P(Z=z)>0/) gleich der Überlebenswahrscheinlichkeit /E(Y | X, Z)/, bedingt auf Testung /X/ und Kovariaten /Z/ ist.

   Dies ist *erfüllt, wenn* /Z/ *all jene Kovariaten umfasst, welche Genesungs-/Sterbewahrscheinlichkeit einer Person beeinflussen.*

   Daher ist eine umfangreiche Erfassung und Veröffentlichung aller Risiko und Protektivfaktoren der Erkrankten notwendig.

2. Positive Testung /X/ und Auswahlwahrscheinlichkeit /U/ stochastisch unabhängig gegeben /Z/ sind. 

   Das Ziel der selektiven Testung durch Kontaktnachverfolgung ist, die Infizierten mit größerer wahrscheinlicher zu testen als die wahrscheinlich nicht Infizierten.  Wenn dieses Ziel erreicht wird, ist diese Bedingung *nicht erfüllt*.

3. Personen-Infektions-Homogenität /E(Y | X,U)/ = E(Y | X) gegeben ist.

   Dies ist *nicht erfüllt*, da offenbar nicht alle test-positiven Personen die gleichen Wahrscheinlichkeiten zu genesen und zu versterben haben.
Nur die erste dieser Bedingungen ist erfüllbar, wenn aufgrund der Testkapazitäten nicht randomisiert getestet wird (2.).
Daher ist es nötig, umfangreiche Patientendaten zur Verfügung zu stellen.

Auf Basis einer repräsentativen Erhebung von Antikörpern scheint Bedingung 2. erfüllt, und eine Einschränkung der Personendaten auf bestimmte Fragestellungen wie Alter, Geschlecht, bestimmte Vorerkrankungen ist hinreichend.
Jedoch selbst in diesem Fall ist es vorteilhaft, möglichst umfangreiche Patientendaten zu veröffentlichen, um Kovariaten zu identifizieren, die einen Einfluss auf den Verlauf der Erkrankung haben, an die aber a-priori niemand gedacht hat.

Steyer, R., Nachtigall, C., Wüthrich-Martone, O., & Kraus, K. (2002). Causal regression models III: Covariates, conditional, and unconditional average causal effects. Methods of Psychological Research Online, 7(1), 41–68.


**** Durchschnittliche kausale Effekte
Wenn die /Z */-bedingte kausale Regression* /E_{Z=z}(Y | X)/ kausal erwartungstreu ist, und die Verteilung der Kovariaten in der Gesamtbevölkerung bekannt ist,  /P'(Z=z)/ ist es möglich, die durchschnittlichen kausalen Effekte in der Gesamtbevölkerung zu berechnen (/P'(Z)/ kann von der Verteilung /P(Z)/ in der getesteten Stichprobe abweichen! Dies ist insbesondere der Fall, wenn nur in symptomatische Patienten in Krankenhäusern getestet werden.).

Die zu erwartende durchschnittliche Mortalitätsrate von Covid19 in der Gesamtbevölkerung entspricht dem durchschnittlichen kausalen Effekt /ACE(Y | X) = \sum_{z \in Z(\Omega)} P'(Z=z) ACE_{Z=z}(Y | X)/.

Es ist beweisbar, dass Marginalisierung über /P'(Z=z)/ eine erwartungstreue Schätzung des durchschnittlichen kausalen Effekts ergibt, wenn die Bedingung erfüllt ist, dass /E_{Z=z}(Y | X)/ kausal erwartungstreu ist für alle /z \in Z(\Omega)/.





*** Anmerkungen zur Erweiterung des Zufallsexperiments:
- /X/: Berücksichtigung verschiedener Tests
- Berücksichtigungen der Zeitpunkte von Testungen, ggf. des Krankheitsverlaufs. 
- /Y/: Vielleicht mit Zeitintervall der Genesung 2 Wochen, vielleicht mehrwertig: genesen, hospitalisiert, verstorben.

*** Statistische Modellierung
Kausale Inferenzstatistik selbst ist kein statistisches Modell!
Vielmehr formuliert kausale Inferenzstatistik die abstrakte wahrscheinlichkeitstheoretische Frage, wie kausale Effekte allgemein definiert sind, auch für nicht-randomisierte kontrollierte Studien.
Statistische Modelle werden in einem zweiten Schritt verwendet um die Wahrscheinlichkeiten an Covid-19 zu versterben, bedingt auf Kovariaten und Teststatus in Regressionen zu schätzen.
In diesem zweiten Schritt haben Forscher statistische Modelle zu testen und kritisch auszuwählen, um zu erwartungstreuen Vorhersagen und Abschätzungen ihrer Zuverlässigkeit zu gelangen.

Logistische Regressionen
1. Modelle logit /P(Y=0 | Z_{i}, X) = \alpha_{0} + \alpha_{1} X + \beta Z_{i} + \gamma X Z_{i}/ für alle Kovariaten /Z_{i}/.
2. Haupteffekte und Interaktionseffekte mit /X/: logit /P(Y=0 | Z, X) = \alpha_{0} + \alpha_{1} X + \sum_{i} \beta_{i} Z_{i}  + \sum_{i} \gamma_{i} X Z_{i}/.
3. Komplexere Modelle zur Abschätzung sind denkbar und wünschenswert.  Ich schlage vor, dass diese Daten anonymisiert öffentlich gemacht werden sollten, um einen freien Wettbewerb für die Vorhersage der Mortalität aus den Kovariaten einzuladen.
4. Bei den voraussichtlich großen Fallzahlen ist ggf. eine nonparametrische und modellfreie Vorhersage möglich.

*** Empfehlungen zur aktuellen Datenveröffentlichung
** Wann hilft und wann schadet Intubation als medizinische Maßnahme?  
Diese Frage beginnt erneut formalen Begriffsklärung durch das Zufallsexperiment.
- Zur Testung wird eine SARS-COV2 positive Person /U=u/ in Intensivpflege ausgewählt
- Die Sauerstoffsättigung wird erhoben, /O=o/
- Kovariaten werden erhoben /Z=z/ (Alter, Geschlecht und Vorerkrankungen etc..)
- Wird die Person intubiert (/X=1/) oder wird sie nicht intubiert (/X=0/)
- Verstirbt (/Y=0/) oder heilt (/Y=1/) die Person?

Der bedingte Kausale Effekt der Intubation auf die Genesungswahrscheinlichkeit für Patienten mit /Z=z, O=o/ ist
ACE_{Z=z,O=o}(Y | X) = /P(Y=1 | X=1, Z=z, O=o)-P(Y=1 | X=0, Z=z, O=o)/.


* Benötigte Daten
# <<daten>>
Optimalerweise würden für die Berechnungen folgende anonymisierten Daten zu jedem getesteten Mitbürger verwendet:
- Testdatum Test-Art und Testergebnis
- Vorerkrankungen
- Hospitalisierungsdatum, falls hospitalisiert
- Entlassungsdatum, falls entlassen
- Versterbedatum, falls verstorben
- Obduktionsdaten, falls verfügbar
- Alter, Geschlecht, wenn möglich Lebensumstände (Rauchen, Luftqualität, Stadt, Land, Ernährungsgewohnheiten, etc)
Zur Bestimmung der kausalen Effekte medizinischer Maßnahmen werden zudem benötigt:
- durchgeführte medizinische Maßnahmen (Intubation, Medikamente)

Voraussichtlich sind manche dieser Daten nicht für alle getesteten Personen verfügbar.
In diesem Fall kann mit geeigneten Verteilungsannahmen die Datenlücke ausgeglichen werden (siehe unten).

* Falls Daten fehlen
Zur statistischen Schätzung dieser Größen sind von den Gesundheitsbehörden folgende Daten erfolderlich:
- Anonymisierte Daten aller getesteten Personen (Testergebnis /X=x/ und Kovariaten /Z=z/).
- Verteilung /P(Z=z)/ in der Population.
- Genesen/Versterben /Y=y/.

Falls die Vorerkrankungen nicht Test-negativer Personen nicht verfügbar sind, ist ggf. eine akzeptable Annahme, dass die Vorerkrankungen der Getesteten ebenso verteilt sind wie in der Gesamtpopulation, bedingt auf das Alter.

Da Sterbedaten der negativ getesteten nicht verfügbar sein dürften, könnte ihre Sterberate /P(Y=0 | Z=z,X=0)/ anhand publizierter Mortalitäten der Vorerkrankungen und des Alters pro Jahr abgeschätzt werden.
Selbst wenn diese Sterberaten verfügbar wäre, ist zu klären, ob es nicht aussagekräftiger ist, die Sterberate innerhalb eines Jahres zugrundezulegen.
